class AnimateConsole
{
    private float _animationLength = 0;
    private List<string> _frames = new List<string>();
    private int _frameRate;
    private List<string> _framesForSpinny = new List<string>()
    {
        "|",
        "/",
        "-",
        "\\"
    };
    private List<string> _framesPeriod = new List<string>(){
        "."
    };
    public void SetFramesForSpinny()
    {
         _frames = _framesForSpinny;
    }
    public void SetFramesPeriod()
    {
        _frames = _framesPeriod;
    }
    // public List<string> FramesForSpinny
    // { //this code was generated by the code generator
    //     get { return _framesForSpinny; }
    //     // set { _framesForSpinny = value; }
    // }
    // public List<string> FramesPeriod
    // { //this code was generated by the code generator
    //     get { return _framesPeriod; }
    //     // set { _framesPeriod = value; }
    // }

// Constructor 
    public AnimateConsole(float animationLength, List<string> frames, int frameRate)
    {
        _animationLength = animationLength;
        _frames = frames;
        _frameRate = frameRate;
    }
    // Constructor
    public AnimateConsole(float animationLength, int frameRate)
    {
        _animationLength = animationLength;
        _frameRate = frameRate;
    }
        
    public void Animate()
    {
        int i = 0;
        DateTime start = DateTime.Now;
        DateTime end = start.AddSeconds(_animationLength);
        while (DateTime.Now <= end)
        {
            Console.Write(_frames[i]);
            Thread.Sleep(_frameRate);
            Console.Write("\b\b  \b\b");
            i++;
            if (i >= _frames.Count)
            {
                i = 0;
            }
        }
    }
    public string DisplayCommonMesg(string message)
    {   
        string commonMessage = $"This activity will help you {message}. ";
        return commonMessage;
    }

    public string PickingRanQuests(string[] questions)
    {
        Random random = new Random();
        int index = random.Next(questions.Length);
        return questions[index];
    }
    

}